identifier = "com.example.depth-measurement.triangulation"
entrypoint = ["/entrypoint.sh", "python3", "-u", "/app/main.py"]
app_version = "1.1.0"
assign_frontend_port = true

prepare_container = [
    { type = "COPY", source = "./requirements.txt", target = "./requirements.txt" },
    { type = "RUN", command = "python3.12 -m pip install -r /app/requirements.txt --break-system-packages"}
]

depthai_models = { yaml_path = "./depthai_models" }

[base_image]
api_url = "https://registry-1.docker.io"
service = "registry.docker.io"
oauth_url = "https://auth.docker.io/token"
auth_type = "repository"
auth_name = "luxonis/oakapp-base"
image_name = "luxonis/oakapp-base"
image_tag = "1.3.0"
