ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}

ENV PLATFORM=""
ENV DAI_VERSION=""
ENV DAI_NODES_VERSION=""
ENV PYTHON_VERSION_ENV=""
ENV LOG_LEVEL="INFO"
ENV ROOT_DIR="."
ENV STRICT_MODE="no"

# Install Virtual Display
RUN apt-get update && apt-get install -y \
    ntpdate \
    sudo \
    udev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Copy your project files into the container
# NOTE: If ran inside GH workflow or with HIL --sync-workspace this is not needed
# COPY . /tmp/oak-examples

# Setup Test Command
WORKDIR /tmp/oak-examples

# Define the entrypoint script
ENTRYPOINT ["sh", "-c", "\
    set -e && \
    echo 'Syncing container clock...' && \
    ntpdate -u pool.ntp.org && \
    if [ -z \"$PLATFORM\" ]; then \
    echo 'Error: PLATFORM environment variable is required' && exit 1; \
    fi && \
    echo 'Installing dependencies...' && \
    pip install -r tests/requirements.txt && \
    /root/.local/share/oakctl/oakctl self-update -v $(/root/.local/share/oakctl/oakctl version) &&\
    echo 'Running tests...' && \
    pytest -v -r a --log-cli-level=${LOG_LEVEL} --log-file=out.log --color=yes \
    --depthai-version=${DAI_VERSION} \
    --depthai-nodes-version=${DAI_NODES_VERSION} \
    --environment-variables=DEPTHAI_PLATFORM=${PLATFORM} \
    --platform=${PLATFORM} \
    --python-version=${PYTHON_VERSION_ENV} \
    --device-password=${DEVICE_PASSWORD} \
    --root-dir ${ROOT_DIR} \
    -- tests/test_examples_standalone.py"]
