ARG PYTHON_VERSION=3.10
FROM python:${PYTHON_VERSION}

ENV PLATFORM=""
ENV DAI_VERSION=""
ENV DAI_NODES_VERSION=""
ENV PYTHON_VERSION_ENV=""
ENV LOG_LEVEL="INFO"
ENV ROOT_DIR="."
ENV STRICT_MODE="no"

# Install Virtual Display
RUN apt-get update && apt-get install -y --no-install-recommends \
    ntpsec-ntpdate \
    sudo \
    udev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends \
    libfaketime \
    && rm -rf /var/lib/apt/lists/*
    
# Copy your project files into the container
# If running inside GH Actions/HIL syncs, files are mounted; otherwise copy.
# COPY . /tmp/oak-examples

# Setup Test Command
WORKDIR /tmp/oak-examples

ENTRYPOINT ["sh", "-c", "\
    set -e && \
    echo 'Faking time to Unix epoch...' && \
    export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1 && \
    export FAKETIME='1970-01-01 00:00:00' && \
    date && \
    if [ -z \"$PLATFORM\" ]; then \
        echo 'Error: PLATFORM environment variable is required' && exit 1; \
    fi && \
    echo 'Installing dependencies...' && \
    pip install --no-cache-dir -r tests/requirements.txt && \
    /root/.local/share/oakctl/oakctl self-update -v $(/root/.local/share/oakctl/oakctl version) && \
    echo 'Running tests...' && \
    pytest -v -r a --log-cli-level=${LOG_LEVEL} --log-file=out.log --color=yes \
        --depthai-version=${DAI_VERSION} \
        --depthai-nodes-version=${DAI_NODES_VERSION} \
        --environment-variables=DEPTHAI_PLATFORM=${PLATFORM} \
        --platform=${PLATFORM} \
        --python-version=${PYTHON_VERSION_ENV} \
        --device-password=${DEVICE_PASSWORD} \
        --local-static-registry=${LOCAL_STATIC_REGISTRY} \
        --root-dir ${ROOT_DIR} \
        -- tests/test_examples_standalone.py \
"]
